apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: asrmaster
  name: asrmaster-controller
spec:
  replicas: 1
  selector:
    name: asrmaster
  template:
    metadata:
      labels:
        name: asrmaster
    spec:
      containers:
      - image: gtrail/lucida:all
        command: ['/bin/bash', '-c']
        args: ['cd $LUCIDA_ROOT/speechrecognition/kaldi_gstreamer_asr/ && source $LUCIDA_PYTHON_ENV/bin/activate && python kaldigstserver/master_server.py --port=8081']
        name: asrmaster
        ports:
        - containerPort: 8081
          name: http-server
