apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ms
  name: ms-controller
spec:
  replicas: 1
  selector:
    name: ms
  template:
    metadata:
      labels:
        name: ms
    spec:
      containers:
      - image: gtrail/lucida:all
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDA_ROOT/musicservice/server/ && python server.py']
        name: ms
        ports:
        - containerPort: 8089
          name: thrift
        env:
          - name: GRACENOTE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: apikeys
                key: gracenote-client-id
          - name: GRACENOTE_USER_ID
            valueFrom:
              secretKeyRef:
                name: apikeys
                key: gracenote-user-id
