apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gtrail/lucida:commandcenter
        command: ['/bin/sh', '-c']
        args: ['export ASR_ADDR_PORT=ws://localhost:30001 && env > /tmp/envs.txt && chown -R www-data:www-data $LUCIDA_ROOT/commandcenter && apachectl -DFOREGROUND']
        name: web
        ports:
        - containerPort: 8000
          name: http-server
