apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gtrail/lucida:commandcenter
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDA_ROOT/commandcenter/apache/ && sed -i s/LogLevel\ warn/LogLevel\ debug/ /etc/apache2/sites-available/000-default.conf && export ASR_ADDR_PORT=ws://localhost:30001 && env > envs.txt && chown -R www-data:www-data /usr/local/lucida/lucida/commandcenter && apachectl -DFOREGROUND -e debug']
        name: web
        ports:
        - containerPort: 80
          name: http-server
